apiVersion: apps/v1
kind: Deployment
metadata:
  name: cast-service
spec:
  replicas: {{ .Values.castService.replicas }}
  selector:
    matchLabels:
      app: cast-service
  template:
    metadata:
      labels:
        app: cast-service
    spec:
      containers:
        - name: cast-service
          image: "{{ .Values.castService.image.repository }}:{{ .Values.global.tag }}"
          ports:
            - containerPort: 8000
          env:
            - name: DATABASE_URI
              value: {{ .Values.castService.env.DATABASE_URI }}